import { CategoryFormData, ProductFormData } from '../types/product';

const CATEGORIES: Omit<CategoryFormData, 'status'>[] = [
  { name: 'Lanches', description: 'Sanduiches, burgers e combos completos.' },
  { name: 'Pizzas', description: 'Pizzas salgadas e doces de diversos tamanhos.' },
  { name: 'Bebidas', description: 'Refrigerantes, sucos, agua e drinks sem alcool.' },
  { name: 'Sobremesas', description: 'Doces para finalizar o pedido.' },
];

type ProductSeed = Omit<ProductFormData, 'categoryId' | 'status' | 'image'> & {
  categoryName: string;
};

const PRODUCTS: ProductSeed[] = [
  {
    categoryName: 'Lanches',
    name: 'Burger Artesanal 160g',
    sku: 'BURG-160',
    brand: 'Vendlyhub Kitchen',
    model: 'Classic',
    description: 'Pao brioche, carne 160g, queijo, alface e molho da casa.',
    salePrice: 32.9,
    discount: 2,
    cost: 15.5,
    unit: 'Unidade',
    stockQuantity: 80,
    reservedStock: 0,
    soldQuantity: 0,
    minStock: 10,
    supplier: 'Distribuidora Centro',
    supplierCode: 'SUP-001',
    ean: '7891234567890',
  },
  {
    categoryName: 'Lanches',
    name: 'Combo Burger + Batata',
    sku: 'COMBO-BURG',
    brand: 'Vendlyhub Kitchen',
    model: 'Combo',
    description: 'Burger artesanal com batata frita crocante.',
    salePrice: 44.9,
    discount: 3,
    cost: 22,
    unit: 'Unidade',
    stockQuantity: 60,
    reservedStock: 0,
    soldQuantity: 0,
    minStock: 8,
    supplier: 'Distribuidora Centro',
    supplierCode: 'SUP-001',
    ean: '7891234567891',
  },
  {
    categoryName: 'Pizzas',
    name: 'Pizza Mussarela Grande',
    sku: 'PIZ-MUS-G',
    brand: 'Vendlyhub Kitchen',
    model: 'Tradicional',
    description: 'Mussarela premium, molho de tomate e oregano.',
    salePrice: 56.9,
    discount: 0,
    cost: 29,
    unit: 'Unidade',
    stockQuantity: 40,
    reservedStock: 0,
    soldQuantity: 0,
    minStock: 6,
    supplier: 'Laticinios Brasil',
    supplierCode: 'SUP-014',
    ean: '7891234567892',
  },
  {
    categoryName: 'Pizzas',
    name: 'Pizza Calabresa Grande',
    sku: 'PIZ-CAL-G',
    brand: 'Vendlyhub Kitchen',
    model: 'Tradicional',
    description: 'Calabresa fatiada, cebola roxa e azeitonas.',
    salePrice: 58.9,
    discount: 0,
    cost: 30,
    unit: 'Unidade',
    stockQuantity: 40,
    reservedStock: 0,
    soldQuantity: 0,
    minStock: 6,
    supplier: 'Frios Prime',
    supplierCode: 'SUP-015',
    ean: '7891234567893',
  },
  {
    categoryName: 'Bebidas',
    name: 'Refrigerante Cola 2L',
    sku: 'BEB-COLA-2L',
    brand: 'Cola',
    model: 'PET 2L',
    description: 'Refrigerante cola gelado de 2 litros.',
    salePrice: 12.9,
    discount: 0,
    cost: 6.8,
    unit: 'Unidade',
    stockQuantity: 120,
    reservedStock: 0,
    soldQuantity: 0,
    minStock: 20,
    supplier: 'Bebidas Sul',
    supplierCode: 'SUP-021',
    ean: '7891234567894',
  },
  {
    categoryName: 'Bebidas',
    name: 'Suco Natural Laranja 500ml',
    sku: 'BEB-SUC-LAR',
    brand: 'Fresh',
    model: '500ml',
    description: 'Suco natural de laranja sem adicao de acucar.',
    salePrice: 9.9,
    discount: 0,
    cost: 4.2,
    unit: 'Unidade',
    stockQuantity: 90,
    reservedStock: 0,
    soldQuantity: 0,
    minStock: 15,
    supplier: 'Hortifruti Paulista',
    supplierCode: 'SUP-030',
    ean: '7891234567895',
  },
  {
    categoryName: 'Sobremesas',
    name: 'Brownie com Sorvete',
    sku: 'SOB-BROWNIE',
    brand: 'Vendlyhub Kitchen',
    model: 'Doce',
    description: 'Brownie de chocolate servido com sorvete de creme.',
    salePrice: 18.9,
    discount: 1.5,
    cost: 7.4,
    unit: 'Unidade',
    stockQuantity: 50,
    reservedStock: 0,
    soldQuantity: 0,
    minStock: 8,
    supplier: 'Doces Delicia',
    supplierCode: 'SUP-041',
    ean: '7891234567896',
  },
  {
    categoryName: 'Sobremesas',
    name: 'Pudim Tradicional',
    sku: 'SOB-PUDIM',
    brand: 'Vendlyhub Kitchen',
    model: 'Doce',
    description: 'Fatia de pudim com calda de caramelo.',
    salePrice: 12.5,
    discount: 0,
    cost: 4.5,
    unit: 'Unidade',
    stockQuantity: 70,
    reservedStock: 0,
    soldQuantity: 0,
    minStock: 10,
    supplier: 'Doces Delicia',
    supplierCode: 'SUP-041',
    ean: '7891234567897',
  },
];

export function buildFakeCategories() {
  return CATEGORIES.map((category) => ({
    ...category,
    status: 'active' as const,
  }));
}

export function buildFakeProducts(
  categoryIdsByName: Record<string, string>,
  suffix: string,
): ProductFormData[] {
  return PRODUCTS.map((product) => ({
    name: product.name,
    sku: `${product.sku}-${suffix}`,
    categoryId: categoryIdsByName[product.categoryName],
    brand: product.brand,
    model: product.model,
    description: product.description,
    salePrice: product.salePrice,
    discount: product.discount,
    cost: product.cost,
    unit: product.unit,
    stockQuantity: product.stockQuantity,
    reservedStock: product.reservedStock,
    soldQuantity: product.soldQuantity,
    minStock: product.minStock,
    supplier: product.supplier,
    supplierCode: product.supplierCode,
    ean: product.ean,
    status: 'active',
    image: null,
  }));
}
