/** Allowed establishment type labels (must match DB seed in migrations). */
export const ESTABLISHMENT_TYPE_NAMES = [
  'Restaurantes',
  'Pizzarias',
  'Hamburguerias',
  'Comida brasileira',
  'Comida japonesa / oriental',
  'Comida italiana',
  'Comida árabe',
  'Comida mexicana',
  'Comida chinesa',
  'Comida saudável / fit',
  'Marmitas',
  'Padarias',
  'Confeitarias',
  'Docerias',
  'Sorveterias',
  'Lojas de açaí',
  'Cafeterias',
  'Casas de sucos',
  'Bares (com regras para bebidas alcoólicas)',
  'Lanchonetes',
  'Pastelarias',
  'Creperias',
  'Food trucks',
  'Cozinhas virtuais (dark kitchens)',
  'Mercados',
  'Minimercados',
  'Hortifrúti',
  'Lojas de conveniência',
  'Empórios',
  'Adegas',
  'Farmácias',
  'Pet shops',
] as const;

export type EstablishmentTypeName = (typeof ESTABLISHMENT_TYPE_NAMES)[number];
